# Generated by Django 4.2.1 on 2023-05-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="profile_image_url",
            field=models.URLField(blank=True),
        ),
    ]
