# Generated by Django 4.2.1 on 2023-05-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_myuser_profile_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="profile_image",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="profile_image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
