# Generated by Django 4.2.1 on 2023-05-23 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_myuser_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="followings",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
