# Generated by Django 4.2.1 on 2023-05-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_myuser_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="profile_image_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
