# Generated by Django 4.2.1 on 2023-05-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_myuser_profile_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="profile_image",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
