# Generated by Django 4.2.1 on 2023-05-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_rename_auther_comments_user_articles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
